(function () {
  var js = '';
  js += "window.lock = false;";
  js += "var xy = document.getElementById('pow_xs_XieyiCheck');";
  js += "if (xy) {";
  js += "  xy.checked = true;";
  js += "  window.touzi();";
  js += "} else {";
  js += "  console.log('no xy found');";
  js += "  if (jQuery) {";
  js += "    var cjcheck = window.setInterval(function () {";
  js += "      var cjbtn = $('.Dlb_conList_right.Dlb_cj').filter(function () { return $(this).find('input').val() >= 10000; }).find('.Dlb_cjBtn').first();";
  js += "      if (cjbtn.length) {";
  js += "        window.clearInterval(cjcheck);";
  js += "        cjbtn.click();";
  js += "        var m14check = window.setInterval(function () {";
  js += "          var m14 = $('#msgDiv14:visible .pow_xs_Sub');";
  js += "          if (m14.length) {";
  js += "            window.clearInterval(m14check);";
  js += "            m14.click();";
  js += "          }";
  js += "        }, 200);";
  js += "        var m10check = window.setInterval(function () {";
  js += "          var m10 = $('#msgDiv10:visible .pow_xs_Sub');";
  js += "          if (m10.length) {";
  js += "            window.clearInterval(m10check);";
  js += "            m10.click();";
  js += "          }";
  js += "        }, 200);";
  js += "      }";
  js += "    }, 500);";
  js += "  }";
  js += "}";
  var script = document.createElement('script');
  script.appendChild(document.createTextNode(js));
  document.body.appendChild(script);
})();
